version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/jwt_auth
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongo

volumes:
  mongo-data:
